apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-lvms-clone
  namespace: test-lvms
spec:
  storageClassName: lvms-vg1
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  dataSource:
    kind: PersistentVolumeClaim
    name: test-lvms