apiVersion: velero.io/v1
kind: Restore
metadata:
  name: lvms-partial-backup-01-lvmcluster
  namespace: openshift-adp
  labels:
    velero.io/storage-location: default
  annotations:
    lca.openshift.io/apply-wave: "1"
spec:
  backupName: lvms-partial-backup-01-lvmcluster
---
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: lvms-partial-backup-01-test-lvms
  namespace: openshift-adp
  labels:
    velero.io/storage-location: default
  annotations:
    lca.openshift.io/apply-wave: "2"
spec:
  backupName: lvms-partial-backup-01-test-lvms
  restorePVs: true
  restoreStatus:
    includedResources:
      - logicalvolumes
