apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: test-lvms
  namespace: test-lvms
spec:
  volumeSnapshotClassName: lvms-vg1
  source:
    persistentVolumeClaimName: test-lvms