apiVersion: v1
kind: Pod
metadata:
  name: test-lvms
  namespace: test-lvms
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: test-lvms
  containers:
    - name: container
      image: docker.io/nginxinc/nginx-unprivileged
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: storage