apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-lvms
  namespace: test-lvms
spec:
  storageClassName: lvms-vg1
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem